# Generated by Django 4.0 on 2021-12-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(verbose_name='Next Deadline')),
                ('job_description', models.TextField(verbose_name='Descripton')),
                ('job_url', models.URLField()),
                ('job_email', models.CharField(max_length=200, verbose_name='email')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.stage')),
            ],
        ),
    ]
