# Generated by Django 4.0 on 2021-12-31 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_title', models.CharField(max_length=200)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Next Deadline')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Descripton')),
                ('job_url', models.URLField(blank=True, default='')),
                ('job_email', models.CharField(blank=True, default='', max_length=200, verbose_name='email')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.stage')),
            ],
        ),
    ]
