# Generated by Django 4.0 on 2021-12-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_alter_posting_deadline_alter_posting_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripton'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='job_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='job_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.stage'),
        ),
    ]
