# Generated by Django 4.0 on 2022-01-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_posting_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
