# Generated by Django 4.0 on 2021-12-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_alter_posting_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='job_email',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='job_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
