# Generated by Django 3.2.10 on 2022-01-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
