# Generated by Django 4.0 on 2021-12-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_stage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='author',
        ),
    ]
